##
## WORKSHOP INFORMATION
##
WEEKDAY_DATA=Thursday
DAY_DATA=19
MONTH_DATA=01
YEAR_DATA=2022
ROOM_DATA=TBA
LOCATION_DATA="Budapest, HU"
PARMA_DATA=13
DITAM_DATA=11
SUBMISSION_LINK_DATA='https://easychair.org/conferences/?conf=parmaditam2022'


##
## WORKSHOP DEADLINES
##

SUBMISSION_IS_TBA=1
SUBMISSION_DAY_DATA=TBA
SUBMISSION_MONTH_DATA=TBA
SUBMISSION_YEAR_DATA=TBA

ACCEPTANCE_DAY_DATA=TBA
ACCEPTANCE_MONTH_DATA=TBA
ACCEPTANCE_YEAR_DATA=TBA

CAMERA_DAY_DATA=TBA
CAMERA_MONTH_DATA=TBA
CAMERA_YEAR_DATA=TBA

X_SUBMISSION_DAY_DATA=TBA
X_SUBMISSION_MONTH_DATA=TBA
X_SUBMISSION_YEAR_DATA=TBA

X_ACCEPTANCE_DAY_DATA=TBA
X_ACCEPTANCE_MONTH_DATA=TBA
X_ACCEPTANCE_YEAR_DATA=TBA

X_CAMERA_DAY_DATA=TBA
X_CAMERA_MONTH_DATA=TBA
X_CAMERA_YEAR_DATA=TBA