#!/bin/bash

# where information lives
DATA_DIR=`pwd`/../.data
YEAR_FILENAME=${DATA_DIR}/YEAR
MONTH_FILENAME=$DATA_DIR/MONTH
DAY_FILENAME=$DATA_DIR/DAY
WEEKDAY_FILENAME=$DATA_DIR/WEEKDAY
LOCATION_FILENAME=${DATA_DIR}/LOCATION
ROOM_FILENAME=$DATA_DIR/ROOM
PARMA_FILENAME=${DATA_DIR}/PARMA
DITAM_FILENAME=${DATA_DIR}/DITAM
SUBMISSION_LINK_FILENAME=${DATA_DIR}/SUBMISSION_LINK

SUBMISSION_DEADLINE_DAY_FILENAME=${DATA_DIR}/deadlines/SUBMISSION_DAY
SUBMISSION_DEADLINE_MONTH_FILENAME=${DATA_DIR}/deadlines/SUBMISSION_MONTH
SUBMISSION_DEADLINE_YEAR_FILENAME=${DATA_DIR}/deadlines/SUBMISSION_YEAR
ACCEPTANCE_DEADLINE_DAY_FILENAME=${DATA_DIR}/deadlines/ACCEPTANCE_DAY
ACCEPTANCE_DEADLINE_MONTH_FILENAME=${DATA_DIR}/deadlines/ACCEPTANCE_MONTH
ACCEPTANCE_DEADLINE_YEAR_FILENAME=${DATA_DIR}/deadlines/ACCEPTANCE_YEAR
CAMERA_DEADLINE_DAY_FILENAME=${DATA_DIR}/deadlines/CAMERA_DAY
CAMERA_DEADLINE_MONTH_FILENAME=${DATA_DIR}/deadlines/CAMERA_MONTH
CAMERA_DEADLINE_YEAR_FILENAME=${DATA_DIR}/deadlines/CAMERA_YEAR

X_SUBMISSION_DEADLINE_DAY_FILENAME=${DATA_DIR}/deadlines/X_SUBMISSION_DAY
X_SUBMISSION_DEADLINE_MONTH_FILENAME=${DATA_DIR}/deadlines/X_SUBMISSION_MONTH
X_SUBMISSION_DEADLINE_YEAR_FILENAME=${DATA_DIR}/deadlines/X_SUBMISSION_YEAR
X_ACCEPTANCE_DEADLINE_DAY_FILENAME=${DATA_DIR}/deadlines/X_ACCEPTANCE_DAY
X_ACCEPTANCE_DEADLINE_MONTH_FILENAME=${DATA_DIR}/deadlines/X_ACCEPTANCE_MONTH
X_ACCEPTANCE_DEADLINE_YEAR_FILENAME=${DATA_DIR}/deadlines/X_ACCEPTANCE_YEAR
X_CAMERA_DEADLINE_DAY_FILENAME=${DATA_DIR}/deadlines/X_CAMERA_DAY
X_CAMERA_DEADLINE_MONTH_FILENAME=${DATA_DIR}/deadlines/X_CAMERA_MONTH
X_CAMERA_DEADLINE_YEAR_FILENAME=${DATA_DIR}/deadlines/X_CAMERA_YEAR

# files to operate on
TEMPLATE_FILE_INDEX=`pwd`/_index.html
TMP_FILE_INDEX=`pwd`/index_tmp.html
FINAL_FILE_INDEX=`pwd`/../index.html

TEMPLATE_FILE_PROGRAM=`pwd`/_program.html
TMP_FILE_PROGRAM=`pwd`/program_tmp.html
FINAL_FILE_PROGRAM=`pwd`/../program.html

# placeholders in the template
ESCAPE_PREFIX=__
ESCAPE_SUFFIX=__

WEEKDAY_PLACEHOLDER=${ESCAPE_PREFIX}WEEKDAY${ESCAPE_SUFFIX}
DAY_PLACEHOLDER=${ESCAPE_PREFIX}DAY${ESCAPE_SUFFIX}
MONTH_PLACEHOLDER=${ESCAPE_PREFIX}MONTH${ESCAPE_SUFFIX}
YEAR_PLACEHOLDER=${ESCAPE_PREFIX}YEAR${ESCAPE_SUFFIX}
ROOM_PLACEHOLDER=${ESCAPE_PREFIX}ROOM${ESCAPE_SUFFIX}
LOCATION_PLACEHOLDER=${ESCAPE_PREFIX}LOCATION${ESCAPE_SUFFIX}
PARMA_PLACEHOLDER=${ESCAPE_PREFIX}PARMA${ESCAPE_SUFFIX}
DITAM_PLACEHOLDER=${ESCAPE_PREFIX}DITAM${ESCAPE_SUFFIX}
SUBMISSION_LINK_PLACEHOLDER=${ESCAPE_PREFIX}SUBMISSION_LINK${ESCAPE_SUFFIX}

SUBMISSION_DAY_PLACEHOLDER=${ESCAPE_PREFIX}SUBMISSION_DAY${ESCAPE_SUFFIX}
SUBMISSION_MONTH_PLACEHOLDER=${ESCAPE_PREFIX}SUBMISSION_MONTH${ESCAPE_SUFFIX}
SUBMISSION_YEAR_PLACEHOLDER=${ESCAPE_PREFIX}SUBMISSION_YEAR${ESCAPE_SUFFIX}

ACCEPTANCE_DAY_PLACEHOLDER=${ESCAPE_PREFIX}ACCEPTANCE_DAY${ESCAPE_SUFFIX}
ACCEPTANCE_MONTH_PLACEHOLDER=${ESCAPE_PREFIX}ACCEPTANCE_MONTH${ESCAPE_SUFFIX}
ACCEPTANCE_YEAR_PLACEHOLDER=${ESCAPE_PREFIX}ACCEPTANCE_YEAR${ESCAPE_SUFFIX}

CAMERA_DAY_PLACEHOLDER=${ESCAPE_PREFIX}CAMERA_DAY${ESCAPE_SUFFIX}
CAMERA_MONTH_PLACEHOLDER=${ESCAPE_PREFIX}CAMERA_MONTH${ESCAPE_SUFFIX}
CAMERA_YEAR_PLACEHOLDER=${ESCAPE_PREFIX}CAMERA_YEAR${ESCAPE_SUFFIX}

X_SUBMISSION_DAY_PLACEHOLDER=${ESCAPE_PREFIX}X_SUBMISSION_DAY${ESCAPE_SUFFIX}
X_SUBMISSION_MONTH_PLACEHOLDER=${ESCAPE_PREFIX}X_SUBMISSION_MONTH${ESCAPE_SUFFIX}
X_SUBMISSION_YEAR_PLACEHOLDER=${ESCAPE_PREFIX}X_SUBMISSION_YEAR${ESCAPE_SUFFIX}

X_ACCEPTANCE_DAY_PLACEHOLDER=${ESCAPE_PREFIX}X_ACCEPTANCE_DAY${ESCAPE_SUFFIX}
X_ACCEPTANCE_MONTH_PLACEHOLDER=${ESCAPE_PREFIX}X_ACCEPTANCE_MONTH${ESCAPE_SUFFIX}
X_ACCEPTANCE_YEAR_PLACEHOLDER=${ESCAPE_PREFIX}X_ACCEPTANCE_YEAR${ESCAPE_SUFFIX}

X_CAMERA_DAY_PLACEHOLDER=${ESCAPE_PREFIX}X_CAMERA_DAY${ESCAPE_SUFFIX}
X_CAMERA_MONTH_PLACEHOLDER=${ESCAPE_PREFIX}X_CAMERA_MONTH${ESCAPE_SUFFIX}
X_CAMERA_YEAR_PLACEHOLDER=${ESCAPE_PREFIX}X_CAMERA_YEAR${ESCAPE_SUFFIX}

# fetch data
WEEKDAY_DATA=`cat ${WEEKDAY_FILENAME}`
DAY_DATA=`cat ${DAY_FILENAME}`
MONTH_DATA=`cat ${MONTH_FILENAME}`
YEAR_DATA=`cat ${YEAR_FILENAME}`
ROOM_DATA=`cat ${ROOM_FILENAME}`
LOCATION_DATA=`cat ${LOCATION_FILENAME}`
PARMA_DATA=`cat ${PARMA_FILENAME}`
DITAM_DATA=`cat ${DITAM_FILENAME}`
SUBMISSION_LINK_DATA=`cat ${SUBMISSION_LINK_FILENAME}`

# fetch deadlines
SUBMISSION_DAY_DATA=`cat ${SUBMISSION_DEADLINE_DAY_FILENAME}`
SUBMISSION_MONTH_DATA=`cat ${SUBMISSION_DEADLINE_MONTH_FILENAME}`
SUBMISSION_YEAR_DATA=`cat ${SUBMISSION_DEADLINE_YEAR_FILENAME}`

ACCEPTANCE_DAY_DATA=`cat ${ACCEPTANCE_DEADLINE_DAY_FILENAME}`
ACCEPTANCE_MONTH_DATA=`cat ${ACCEPTANCE_DEADLINE_MONTH_FILENAME}`
ACCEPTANCE_YEAR_DATA=`cat ${ACCEPTANCE_DEADLINE_YEAR_FILENAME}`

CAMERA_DAY_DATA=`cat ${CAMERA_DEADLINE_DAY_FILENAME}`
CAMERA_MONTH_DATA=`cat ${CAMERA_DEADLINE_MONTH_FILENAME}`
CAMERA_YEAR_DATA=`cat ${CAMERA_DEADLINE_YEAR_FILENAME}`

X_SUBMISSION_DAY_DATA=`cat ${X_SUBMISSION_DEADLINE_DAY_FILENAME}`
X_SUBMISSION_MONTH_DATA=`cat ${X_SUBMISSION_DEADLINE_MONTH_FILENAME}`
X_SUBMISSION_YEAR_DATA=`cat ${X_SUBMISSION_DEADLINE_YEAR_FILENAME}`

X_ACCEPTANCE_DAY_DATA=`cat ${X_ACCEPTANCE_DEADLINE_DAY_FILENAME}`
X_ACCEPTANCE_MONTH_DATA=`cat ${X_ACCEPTANCE_DEADLINE_MONTH_FILENAME}`
X_ACCEPTANCE_YEAR_DATA=`cat ${X_ACCEPTANCE_DEADLINE_YEAR_FILENAME}`

X_CAMERA_DAY_DATA=`cat ${X_CAMERA_DEADLINE_DAY_FILENAME}`
X_CAMERA_MONTH_DATA=`cat ${X_CAMERA_DEADLINE_MONTH_FILENAME}`
X_CAMERA_YEAR_DATA=`cat ${X_CAMERA_DEADLINE_YEAR_FILENAME}`

# start processing
cp ${TEMPLATE_FILE_INDEX} ${TMP_FILE_INDEX}
cp ${TEMPLATE_FILE_PROGRAM} ${TMP_FILE_PROGRAM}

for WIP_FILE in "${TMP_FILE_PROGRAM}" "${TMP_FILE_INDEX}"
do
	# workshop data
	sed -i "s/${WEEKDAY_PLACEHOLDER}/${WEEKDAY_DATA}/g" ${WIP_FILE}
	sed -i "s/${DAY_PLACEHOLDER}/${DAY_DATA}/g" ${WIP_FILE}
	sed -i "s/${MONTH_PLACEHOLDER}/${MONTH_DATA}/g" ${WIP_FILE}
	sed -i "s/${YEAR_PLACEHOLDER}/${YEAR_DATA}/g" ${WIP_FILE}
	sed -i "s/${ROOM_PLACEHOLDER}/${ROOM_DATA}/g" ${WIP_FILE}
	sed -i "s/${LOCATION_PLACEHOLDER}/${LOCATION_DATA}/g" ${WIP_FILE}
	sed -i "s|${SUBMISSION_LINK_PLACEHOLDER}|${SUBMISSION_LINK_DATA}|" ${WIP_FILE}
	# edition numbers
	sed -i "s/${PARMA_PLACEHOLDER}/${PARMA_DATA}/g" ${WIP_FILE}
	sed -i "s/${DITAM_PLACEHOLDER}/${DITAM_DATA}/g" ${WIP_FILE}

	# deadlines
	sed -i "s/${SUBMISSION_DAY_PLACEHOLDER}/${SUBMISSION_DAY_DATA}/g" ${WIP_FILE}
	sed -i "s/${SUBMISSION_MONTH_PLACEHOLDER}/${SUBMISSION_MONTH_DATA}/g" ${WIP_FILE}
	sed -i "s/${SUBMISSION_YEAR_PLACEHOLDER}/${SUBMISSION_YEAR_DATA}/g" ${WIP_FILE}
	sed -i "s/${ACCEPTANCE_DAY_PLACEHOLDER}/${ACCEPTANCE_DAY_DATA}/g" ${WIP_FILE}
	sed -i "s/${ACCEPTANCE_MONTH_PLACEHOLDER}/${ACCEPTANCE_MONTH_DATA}/g" ${WIP_FILE}
	sed -i "s/${ACCEPTANCE_YEAR_PLACEHOLDER}/${ACCEPTANCE_YEAR_DATA}/g" ${WIP_FILE}
	sed -i "s/${CAMERA_DAY_PLACEHOLDER}/${CAMERA_DAY_DATA}/g" ${WIP_FILE}
	sed -i "s/${CAMERA_MONTH_PLACEHOLDER}/${CAMERA_MONTH_DATA}/g" ${WIP_FILE}
	sed -i "s/${CAMERA_YEAR_PLACEHOLDER}/${CAMERA_YEAR_DATA}/g" ${WIP_FILE}

	# extended deadlines
	sed -i "s/${X_SUBMISSION_DAY_PLACEHOLDER}/${X_SUBMISSION_DAY_DATA}/g" ${WIP_FILE}
	sed -i "s/${X_SUBMISSION_MONTH_PLACEHOLDER}/${X_SUBMISSION_MONTH_DATA}/g" ${WIP_FILE}
	sed -i "s/${X_SUBMISSION_YEAR_PLACEHOLDER}/${X_SUBMISSION_YEAR_DATA}/g" ${WIP_FILE}
	sed -i "s/${X_ACCEPTANCE_DAY_PLACEHOLDER}/${X_ACCEPTANCE_DAY_DATA}/g" ${WIP_FILE}
	sed -i "s/${X_ACCEPTANCE_MONTH_PLACEHOLDER}/${X_ACCEPTANCE_MONTH_DATA}/g" ${WIP_FILE}
	sed -i "s/${X_ACCEPTANCE_YEAR_PLACEHOLDER}/${X_ACCEPTANCE_YEAR_DATA}/g" ${WIP_FILE}
	sed -i "s/${X_CAMERA_DAY_PLACEHOLDER}/${X_CAMERA_DAY_DATA}/g" ${WIP_FILE}
	sed -i "s/${X_CAMERA_MONTH_PLACEHOLDER}/${X_CAMERA_MONTH_DATA}/g" ${WIP_FILE}
	sed -i "s/${X_CAMERA_YEAR_PLACEHOLDER}/${X_CAMERA_YEAR_DATA}/g" ${WIP_FILE}
done

mv ${TMP_FILE_INDEX} ${FINAL_FILE_INDEX}
mv ${TMP_FILE_PROGRAM} ${FINAL_FILE_PROGRAM}
