#!/bin/bash -x

# files to operate on
TEMPLATE_FILE_GLOB_HEAD=`pwd`/__global_head.html
TEMPLATE_FILE_GLOB_FOOT=`pwd`/__global_foot.html

TEMPLATE_FILE_INDEX=`pwd`/_index.html
TMP_FILE_INDEX=`pwd`/index_tmp.html
FINAL_FILE_INDEX=`pwd`/../index.html

TEMPLATE_FILE_PROGRAM=`pwd`/_program.html
TMP_FILE_PROGRAM=`pwd`/program_tmp.html
FINAL_FILE_PROGRAM=`pwd`/../program.html

TEMPLATE_FILE_GUIDELINES=`pwd`/_submission.html
TMP_FILE_GUIDELINES=`pwd`/submission_tmp.html
FINAL_FILE_GUIDELINES=`pwd`/../Submission_Guidelines.html

# placeholders in the template
ESCAPE_PREFIX=__
ESCAPE_SUFFIX=__

WEEKDAY_PLACEHOLDER=${ESCAPE_PREFIX}WEEKDAY${ESCAPE_SUFFIX}
DAY_PLACEHOLDER=${ESCAPE_PREFIX}DAY${ESCAPE_SUFFIX}
MONTH_PLACEHOLDER=${ESCAPE_PREFIX}MONTH${ESCAPE_SUFFIX}
YEAR_PLACEHOLDER=${ESCAPE_PREFIX}YEAR${ESCAPE_SUFFIX}
ROOM_PLACEHOLDER=${ESCAPE_PREFIX}ROOM${ESCAPE_SUFFIX}
LOCATION_PLACEHOLDER=${ESCAPE_PREFIX}LOCATION${ESCAPE_SUFFIX}
PARMA_PLACEHOLDER=${ESCAPE_PREFIX}PARMA${ESCAPE_SUFFIX}
DITAM_PLACEHOLDER=${ESCAPE_PREFIX}DITAM${ESCAPE_SUFFIX}
SUBMISSION_LINK_PLACEHOLDER=${ESCAPE_PREFIX}SUBMISSION_LINK${ESCAPE_SUFFIX}

SUBMISSION_DAY_PLACEHOLDER=${ESCAPE_PREFIX}SUBMISSION_DAY${ESCAPE_SUFFIX}
SUBMISSION_MONTH_PLACEHOLDER=${ESCAPE_PREFIX}SUBMISSION_MONTH${ESCAPE_SUFFIX}
SUBMISSION_YEAR_PLACEHOLDER=${ESCAPE_PREFIX}SUBMISSION_YEAR${ESCAPE_SUFFIX}

ACCEPTANCE_DAY_PLACEHOLDER=${ESCAPE_PREFIX}ACCEPTANCE_DAY${ESCAPE_SUFFIX}
ACCEPTANCE_MONTH_PLACEHOLDER=${ESCAPE_PREFIX}ACCEPTANCE_MONTH${ESCAPE_SUFFIX}
ACCEPTANCE_YEAR_PLACEHOLDER=${ESCAPE_PREFIX}ACCEPTANCE_YEAR${ESCAPE_SUFFIX}

CAMERA_DAY_PLACEHOLDER=${ESCAPE_PREFIX}CAMERA_DAY${ESCAPE_SUFFIX}
CAMERA_MONTH_PLACEHOLDER=${ESCAPE_PREFIX}CAMERA_MONTH${ESCAPE_SUFFIX}
CAMERA_YEAR_PLACEHOLDER=${ESCAPE_PREFIX}CAMERA_YEAR${ESCAPE_SUFFIX}

X_SUBMISSION_DAY_PLACEHOLDER=${ESCAPE_PREFIX}X_SUBMISSION_DAY${ESCAPE_SUFFIX}
X_SUBMISSION_MONTH_PLACEHOLDER=${ESCAPE_PREFIX}X_SUBMISSION_MONTH${ESCAPE_SUFFIX}
X_SUBMISSION_YEAR_PLACEHOLDER=${ESCAPE_PREFIX}X_SUBMISSION_YEAR${ESCAPE_SUFFIX}

X_ACCEPTANCE_DAY_PLACEHOLDER=${ESCAPE_PREFIX}X_ACCEPTANCE_DAY${ESCAPE_SUFFIX}
X_ACCEPTANCE_MONTH_PLACEHOLDER=${ESCAPE_PREFIX}X_ACCEPTANCE_MONTH${ESCAPE_SUFFIX}
X_ACCEPTANCE_YEAR_PLACEHOLDER=${ESCAPE_PREFIX}X_ACCEPTANCE_YEAR${ESCAPE_SUFFIX}

X_CAMERA_DAY_PLACEHOLDER=${ESCAPE_PREFIX}X_CAMERA_DAY${ESCAPE_SUFFIX}
X_CAMERA_MONTH_PLACEHOLDER=${ESCAPE_PREFIX}X_CAMERA_MONTH${ESCAPE_SUFFIX}
X_CAMERA_YEAR_PLACEHOLDER=${ESCAPE_PREFIX}X_CAMERA_YEAR${ESCAPE_SUFFIX}

# read config
source ../.data/config.sh

# start processing
cat "$TEMPLATE_FILE_GLOB_HEAD" "$TEMPLATE_FILE_INDEX" "$TEMPLATE_FILE_GLOB_FOOT" > "$TMP_FILE_INDEX"
cat "$TEMPLATE_FILE_GLOB_HEAD" "${TEMPLATE_FILE_PROGRAM}" "$TEMPLATE_FILE_GLOB_FOOT" > "${TMP_FILE_PROGRAM}"
cat "$TEMPLATE_FILE_GLOB_HEAD" "${TEMPLATE_FILE_GUIDELINES}" "$TEMPLATE_FILE_GLOB_FOOT" > "${TMP_FILE_GUIDELINES}"

for WIP_FILE in "${TMP_FILE_PROGRAM}" "${TMP_FILE_INDEX}" "${TMP_FILE_GUIDELINES}"
do
	# workshop data
	sed -i '' "s/${WEEKDAY_PLACEHOLDER}/${WEEKDAY_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${DAY_PLACEHOLDER}/${DAY_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${MONTH_PLACEHOLDER}/${MONTH_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${YEAR_PLACEHOLDER}/${YEAR_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${ROOM_PLACEHOLDER}/${ROOM_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${LOCATION_PLACEHOLDER}/${LOCATION_DATA}/g" ${WIP_FILE}
	sed -i '' "s|${SUBMISSION_LINK_PLACEHOLDER}|${SUBMISSION_LINK_DATA}|" ${WIP_FILE}
	# edition numbers
	sed -i '' "s/${PARMA_PLACEHOLDER}/${PARMA_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${DITAM_PLACEHOLDER}/${DITAM_DATA}/g" ${WIP_FILE}

	# deadlines
	sed -i '' "s/${SUBMISSION_DAY_PLACEHOLDER}/${SUBMISSION_DAY_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${SUBMISSION_MONTH_PLACEHOLDER}/${SUBMISSION_MONTH_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${SUBMISSION_YEAR_PLACEHOLDER}/${SUBMISSION_YEAR_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${ACCEPTANCE_DAY_PLACEHOLDER}/${ACCEPTANCE_DAY_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${ACCEPTANCE_MONTH_PLACEHOLDER}/${ACCEPTANCE_MONTH_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${ACCEPTANCE_YEAR_PLACEHOLDER}/${ACCEPTANCE_YEAR_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${CAMERA_DAY_PLACEHOLDER}/${CAMERA_DAY_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${CAMERA_MONTH_PLACEHOLDER}/${CAMERA_MONTH_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${CAMERA_YEAR_PLACEHOLDER}/${CAMERA_YEAR_DATA}/g" ${WIP_FILE}

	# extended deadlines
	sed -i '' "s/${X_SUBMISSION_DAY_PLACEHOLDER}/${X_SUBMISSION_DAY_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${X_SUBMISSION_MONTH_PLACEHOLDER}/${X_SUBMISSION_MONTH_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${X_SUBMISSION_YEAR_PLACEHOLDER}/${X_SUBMISSION_YEAR_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${X_ACCEPTANCE_DAY_PLACEHOLDER}/${X_ACCEPTANCE_DAY_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${X_ACCEPTANCE_MONTH_PLACEHOLDER}/${X_ACCEPTANCE_MONTH_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${X_ACCEPTANCE_YEAR_PLACEHOLDER}/${X_ACCEPTANCE_YEAR_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${X_CAMERA_DAY_PLACEHOLDER}/${X_CAMERA_DAY_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${X_CAMERA_MONTH_PLACEHOLDER}/${X_CAMERA_MONTH_DATA}/g" ${WIP_FILE}
	sed -i '' "s/${X_CAMERA_YEAR_PLACEHOLDER}/${X_CAMERA_YEAR_DATA}/g" ${WIP_FILE}
done

rm -rf *.bak
mv ${TMP_FILE_INDEX} ${FINAL_FILE_INDEX}
mv ${TMP_FILE_PROGRAM} ${FINAL_FILE_PROGRAM}
mv ${TMP_FILE_GUIDELINES} ${FINAL_FILE_GUIDELINES}
