#!/bin/bash

# where information lives
DATA_DIR=`pwd`/../.data
YEAR_FILENAME=${DATA_DIR}/YEAR
MONTH_FILENAME=$DATA_DIR/MONTH
DAY_FILENAME=$DATA_DIR/DAY
WEEKDAY_FILENAME=$DATA_DIR/WEEKDAY
LOCATION_FILENAME=${DATA_DIR}/LOCATION
ROOM_FILENAME=$DATA_DIR/ROOM
PARMA_FILENAME=${DATA_DIR}/PARMA
DITAM_FILENAME=${DATA_DIR}/DITAM
SUBMISSION_LINK_FILENAME=${DATA_DIR}/SUBMISSION_LINK

# files to operate on
TEMPLATE_FILE_INDEX=`pwd`/_index.html
TMP_FILE_INDEX=`pwd`/index_tmp.html
FINAL_FILE_INDEX=`pwd`/../index.html

TEMPLATE_FILE_PROGRAM=`pwd`/_program.html
TMP_FILE_PROGRAM=`pwd`/program_tmp.html
FINAL_FILE_PROGRAM=`pwd`/../program.html

# placeholders in the template
ESCAPE_PREFIX=__
ESCAPE_SUFFIX=__

WEEKDAY_PLACEHOLDER=${ESCAPE_PREFIX}WEEKDAY${ESCAPE_SUFFIX}
DAY_PLACEHOLDER=${ESCAPE_PREFIX}DAY${ESCAPE_SUFFIX}
MONTH_PLACEHOLDER=${ESCAPE_PREFIX}MONTH${ESCAPE_SUFFIX}
YEAR_PLACEHOLDER=${ESCAPE_PREFIX}YEAR${ESCAPE_SUFFIX}
ROOM_PLACEHOLDER=${ESCAPE_PREFIX}ROOM${ESCAPE_SUFFIX}
LOCATION_PLACEHOLDER=${ESCAPE_PREFIX}LOCATION${ESCAPE_SUFFIX}
PARMA_PLACEHOLDER=${ESCAPE_PREFIX}PARMA${ESCAPE_SUFFIX}
DITAM_PLACEHOLDER=${ESCAPE_PREFIX}DITAM${ESCAPE_SUFFIX}
SUBMISSION_LINK_PLACEHOLDER=${ESCAPE_PREFIX}SUBMISSION_LINK${ESCAPE_SUFFIX}

# fetch data
WEEKDAY_DATA=`cat ${WEEKDAY_FILENAME}`
DAY_DATA=`cat ${DAY_FILENAME}`
MONTH_DATA=`cat ${MONTH_FILENAME}`
YEAR_DATA=`cat ${YEAR_FILENAME}`
ROOM_DATA=`cat ${ROOM_FILENAME}`
LOCATION_DATA=`cat ${LOCATION_FILENAME}`
PARMA_DATA=`cat ${PARMA_FILENAME}`
DITAM_DATA=`cat ${DITAM_FILENAME}`
SUBMISSION_LINK_DATA=`cat ${SUBMISSION_LINK_FILENAME}`

# start processing
cp ${TEMPLATE_FILE_INDEX} ${TMP_FILE_INDEX}
cp ${TEMPLATE_FILE_PROGRAM} ${TMP_FILE_PROGRAM}

for WIP_FILE in "${TMP_FILE_PROGRAM}" "${TMP_FILE_INDEX}"
do
	sed -i "s/${WEEKDAY_PLACEHOLDER}/${WEEKDAY_DATA}/g" ${WIP_FILE}
	sed -i "s/${DAY_PLACEHOLDER}/${DAY_DATA}/g" ${WIP_FILE}
	sed -i "s/${MONTH_PLACEHOLDER}/${MONTH_DATA}/g" ${WIP_FILE}
	sed -i "s/${YEAR_PLACEHOLDER}/${YEAR_DATA}/g" ${WIP_FILE}
	sed -i "s/${ROOM_PLACEHOLDER}/${ROOM_DATA}/g" ${WIP_FILE}
	sed -i "s/${LOCATION_PLACEHOLDER}/${LOCATION_DATA}/g" ${WIP_FILE}
	sed -i "s/${PARMA_PLACEHOLDER}/${PARMA_DATA}/g" ${WIP_FILE}
	sed -i "s/${DITAM_PLACEHOLDER}/${DITAM_DATA}/g" ${WIP_FILE}
	sed -i "s|${SUBMISSION_LINK_PLACEHOLDER}|${SUBMISSION_LINK_DATA}|" ${WIP_FILE}
done

mv ${TMP_FILE_INDEX} ${FINAL_FILE_INDEX}
mv ${TMP_FILE_PROGRAM} ${FINAL_FILE_PROGRAM}
